
name: Kubernetes Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.26.0'

    - name: Set up Kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Test Pods
      run: bash ./tests/test_pods.sh

    - name: Test Service
      run: bash ./tests/test_service.sh