apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
        - name: book-app-container
          image: aicha814/book-app:latest  # Remplacer par l'image que tu veux utiliser
          ports:
            - containerPort: 80
