apiVersion: v1
kind: Config
clusters:
- name: minikube
  cluster:
    certificate-authority: ./k8s/certs/ca.crt
    server: https://127.0.0.1:54582
contexts:
- name: minikube
  context:
    cluster: minikube
    user: minikube
current-context: minikube
users:
- name: minikube
  user:
    client-certificate: ./k8s/certs/client.crt
    client-key: ./k8s/certs/client.key
