apiVersion: v1
kind: Pod
metadata:
  name: book-app-pod
spec:
  containers:
    - name: book-app-container
      image: aicha814/book-app:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
