apiVersion: v1
kind: Pod
metadata:
  name: book-app-pod
spec:
  containers:
    - name: book-app-container
      image: aicha814/book-app:latest  # Remplacer par l'image que tu veux utiliser (locale ou depuis Docker Hub)
      ports:
        - containerPort: 80
