apiVersion: v1
kind: Service
metadata:
  name: book-app-service
spec:
  selector:
    app: book-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
