name: CI/CD Pipeline for Book App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build -t book-app .
    - name: Push Docker Image to Docker Hub
      run: docker push aicha814/book-app:latest
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
    - name: Run Tests
      run: |
        # Ajouter des tests ici
