name: CI/CD Book App

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t aicha814/book-app:latest .

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image
        run: docker push aicha814/book-app:latest

      # Optionnel : Apply manifests to Kubernetes (si accès)
      # - name: Deploy to K8s
      #   run: |
      #     kubectl apply -f k8s/
