name: CI/CD - Book App Deployment

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v3

      - name:  Set up Docker credentials
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name:  Build Docker image
        run: docker build -t aicha814/book-app:latest .

      - name: Liste des images Docker
        run: docker images

      - name:  Push image to Docker Hub
        run: docker push aicha814/book-app:latest

      - name:  Setup Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: 📦 Deploy to Kubernetes
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: 🧪 Run test script
        run: |
          chmod +x tests/test.sh
          bash tests/test.sh
